proxmox_url          = "https://pve-01.lan.homelab:8006/api2/json"
node                 = "pve-01"
vm_id                = 912
build_name           = "ubuntu"
vm_name              = "ubuntu-24-04-server-std-docker"
clone_vm             = "ubuntu-24-04-server-standard"
template_description = "Ubuntu server 24.04 template with Docker installed generated by Packer on {{ isotime `2006-01-02` }}."
