build_name = "ubuntu"
clone_vm   = "ubuntu-22-04-server-standard"

vm_id                = 903
vm_name              = "ubuntu-22-04-server-std-docker"
template_description = "Ubuntu server 22.04 template with Docker installed generated by Packer on {{ isotime `2006-01-02` }}."
